name: TestE2E

on:
  workflow_run:
    branches:
      - '**'
    workflows: [Build node_modules]        
    types:
      - completed

jobs:
  cypress-run: 
    name: Run Test E2E
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node-modules-artifact

      - name: unzip artifact for node_modules
        run: unzip node_modules.zip

      - name: Build Front local image
        run: |
          docker build -t getlago/front:ci ./

      - name: Checkout API Git repository
        uses: actions/checkout@v3
        with:
          repository: getlago/lago-api
          ref: ${{ github.event.inputs.api_branch }}
          path: api
          token: ${{ secrets.GH_TOKEN }}

      - name: Build API local image
        run: |
          docker build -t getlago/api:ci ./api
      
      - name: Generate API RSA Key
        run: |
          echo "LAGO_RSA_PRIVATE_KEY=\"`openssl genrsa 2048 | base64`\"" >> .env

      - name: Launch APP + API
        run: |
          docker-compose -f ./api/docker-compose.ci.yml -f docker-compose.ci.yml --env-file ./.env up -d redis api front

      - name: Cypress run
        uses: cypress-io/github-action@v4
        env: 
          CYPRESS_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          browser: chrome
          record: true
          config: baseUrl=http://localhost,projectId=u863yi
