name: Tests

on:
  workflow_run:
    branches:
      - '**'
    workflows: [Build node_modules]        
    types:
      - completed

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Download node_modules artifact
        uses: actions/download-artifact@v3
        with:
          name: node-modules-artifact

      - name: unzip artifact for node_modules
        run: unzip node_modules.zip

      - name: Run tests
        run: |
          yarn test
